variables:
  TF_VAR_FILE: "$CI_PROJECT_DIR/tests/variables.tfvars"
  AWS_KUBE_CI_PARAMS: "--driver --k8s-plugin --nvcr"

image: alpine

stages:
  - aws_kube_setup
  - test_setup
  - aws_kube_clean
  - test_cleanup

before_script:
  - mkdir -p aws-kube-ci
  - cp * aws-kube-ci/ || true

aws_kube_setup:
  extends: .aws_kube_setup
  except:
    - schedules


test_setup:
  stage: test_setup
  except:
    - schedules
  script:
    - apk add openssh-client
    - cd tests && ./test_setup.sh

aws_kube_clean:
  extends: .aws_kube_clean
  except:
    - schedules

test_cleanup:
  stage: test_cleanup
  except:
    - schedules
  script:
    - apk add openssh-client
    - cd tests && ./test_cleanup.sh

include:
  - local: 'aws-kube-ci.yml'

cleanup:
  stage: test_cleanup
  only:
    - schedules
  image:
    name: amazon/aws-cli
    entrypoint: ["/bin/bash", "-c"]
  script:
    - export AWS_DEFAULT_REGION="us-west-2"
    - bash -x cleanup/run.sh

